class Song {
  final String id;
  final String title;
  final String artist;
  final String album;
  final String? albumArt;
  final String filePath;
  final Duration duration;
  final int playCount;
  final DateTime? lastPlayed;

  Song({
    required this.id,
    required this.title,
    required this.artist,
    required this.album,
    this.albumArt,
    required this.filePath,
    required this.duration,
    this.playCount = 0,
    this.lastPlayed,
  });
}

class Album {
  final String id;
  final String name;
  final String artist;
  final String? artPath;
  final List<Song> songs;
  final int playCount;

  Album({
    required this.id,
    required this.name,
    required this.artist,
    this.artPath,
    required this.songs,
    this.playCount = 0,
  });
}

class Artist {
  final String id;
  final String name;
  final String? imagePath;
  final List<Song> songs;
  final int playCount;

  Artist({
    required this.id,
    required this.name,
    this.imagePath,
    required this.songs,
    this.playCount = 0,
  });
}

class Playlist {
  final String id;
  final String name;
  final String? coverArt;
  final List<Song> songs;
  final bool isAutoGenerated;
  final DateTime createdAt;

  Playlist({
    required this.id,
    required this.name,
    this.coverArt,
    required this.songs,
    this.isAutoGenerated = false,
    required this.createdAt,
  });
}
